name: Create Release
on:
  pull_request:
    branches:
      - main
    types: [closed]
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Check latest tag
        uses: actions/github-script@v4
        id: latest-tag
        with:
          script: |
            const a = ${{context.payload.pull_request.title}};
            console.log(a);
